kind: pipeline
name: php7-mysql

services:
    - name: db
      image: mysql
      environment:
          MYSQL_USERNAME: friendica
          MYSQL_PASSWORD: friendica
          MYSQL_DATABASE: friendica
          MYSQL_ADMIN_PASSWORD: friendica
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

steps:
    - name: seed-db
      image: mysql
      commands:
          # Ensure db node is still running
          - ping -c1 db
          # Wait for the mysql service to be ready.
          - while (! mysqladmin ping -h db --silent); do sleep 1; done
          - mysql -u root -h db friendica < database.sql

    - name: install
      image: composer
      commands:
          - composer install

    - name: test
      image: php:7
      environment:
        MYSQL_USERNAME: friendica
        MYSQL_PASSWORD: friendica
        MYSQL_DATABASE: friendica
        MYSQL_HOST: db
        MYSQL_PORT: "3306"
      commands:
          - vendor/bin/phpunit --configuration phpunit.xml